added migration logic using go-migrate for mongo

diff --git a/taskfile.yaml b/taskfile.yaml
--- a/taskfile.yaml
+++ b/taskfile.yaml
@@ -26,8 +26,34 @@ tasks:
 
 
   migrations:new:
+    desc: create a new migration
+    vars:
+      NAME: '{{.name | default ""}}'
+    cmds:
+    - |
+      if [ -z "{{.NAME}}"]; then
+        echo "Error :Name paramter is required"
+        echo "Usage : task migrations name=migration_name"
+        exit 1
+      fi
+    - echo 'Creating migration file for {{.NAME}}...'
+    - migrate create -ext json -dir ./internal/database/migrations -seq {{.NAME}}
 
   migrations:up:
+    desc: apply all up database migrations
+    deps: [ confirm ]
+    cmds:
+    - echo 'Running up migrations...'
+    -  migrate -path ./internal/database/migrations -database "{{.DB_URI}}" up
+
+    migrations:down:
+    desc: apply all down migrations
+    deps : [ comfirm ]
+    cmd:
+    - echo 'Reverting last migration...'
+    #down 1 means go back 1 version , just down destroys everything
+
+    - migrate -path ./internal/database/migrations -database "{{.DB_URI}}" down 1
 
 
   tidy:
